### ISSUE TITLE
Fails to build on Fedora with bmake

### ISSUE THREAD

**Issue by calebccff** [katef/libfsm#328] opened 2021-03-24 04:06 UTC
Hi! I'm trying to build libfsm on Fedora, I've installed the bmake package and running `bmake -r install` produces the following errors:
```
bmake: "/usr/share/mk/subdir.mk" line 93: Inconsistent operator for all
bmake: "/usr/share/mk/subdir.mk" line 93: Inconsistent operator for clean
bmake: "/usr/share/mk/init.mk" line 85: Inconsistent operator for all
bmake: "/usr/share/mk/subdir.mk" line 102: Inconsistent operator for all
bmake: "/home/caleb/git/libfsm/Makefile" line 88: Could not find pc.mk
bmake: "/home/caleb/git/libfsm/Makefile" line 89: Could not find sid.mk
bmake: "/home/caleb/git/libfsm/Makefile" line 90: Could not find pkgconf.mk
bmake: "/home/caleb/git/libfsm/Makefile" line 91: Could not find lx.mk
bmake: "/usr/share/mk/obj.mk" line 46: Malformed conditional (${MK_AUTO_OBJ} == "yes")
bmake: "/home/caleb/git/libfsm/Makefile" line 94: Could not find ar.mk
bmake: "/home/caleb/git/libfsm/Makefile" line 95: Could not find so.mk
bmake: "/home/caleb/git/libfsm/Makefile" line 96: Could not find part.mk
bmake: "/usr/share/mk/prog.mk" line 140: Inconsistent operator for all
bmake: "/usr/share/mk/subdir.mk" line 102: Inconsistent operator for all
bmake: "/usr/share/mk/final.mk" line 11: Malformed conditional (${MK_STAGING} == "yes")
bmake: "/usr/share/mk/final.mk" line 18: Inconsistent operator for install
bmake: "/home/caleb/git/libfsm/Makefile" line 98: Could not find mkdir.mk
bmake: "/home/caleb/git/libfsm/Makefile" line 105: Could not find install.mk
bmake: "/home/caleb/git/libfsm/Makefile" line 106: Could not find clean.mk
bmake: Fatal errors encountered -- cannot continue
bmake: stopped in /home/caleb/git/libfsm
```

**Comment by mingodad** [comment] 2021-04-04 17:20
Also on Ubuntu 18.04 it freezes here:
```
pmake 
pmake: "share/mk/share/mk/mkdir.mk" line 39: warning: duplicate script for target "build/pc" ignored
pmake: "share/mk/share/mk/pc.mk" line 19: warning: using previous script for "build/pc" defined here
sed    -e 's,@prefix@,/usr/local,g'  > build/pc
```

**Comment by katef** [comment] 2021-04-08 21:53
hi @calebccff, did you clone with submodules? it looks like you're missing the makefiles entirely.
```
; git clone --recursive https://github.com/katef/libfsm.git
```

**Comment by katef** [comment] 2021-04-08 21:56
@mingodad that's interesting. that looks like some variable isn't being set, I presume because of the duplicate rule overriding a target. I'll try to reproduce that, thank you.

**Comment by katef** [comment] 2023-04-12 05:28
#406 is an attempt to address the "Inconsistent operator" errors with newer bmakes. Possibly for different reasons, I'm not sure.

**Comment by katef** [comment] 2024-08-24 14:14
Closing this ticket because it's confusing separate issues. I think #406 resolved the only bug here. Please open a new ticket if I did miss something, thank you

**Closed by katef** 2024-08-24 14:14 UTC
Labels: bug
