### ISSUE TITLE
bug: non-minimal DFA produced by fsm_minimise

### ISSUE THREAD

**Issue by dgryski** [katef/libfsm#404] opened 2023-04-10 21:28 UTC
Once a match is found, the result should be returned immediately without walking the rest of the string to figure out capture group 0.

**Comment by katef** [comment] 2023-04-11 05:19
minimal test case:
```
./build/bin/re -r pcre -pl dot  'ab*c'
```
git bisects finds [ff5fb750731778c051d6789e5d67797830f7da7a](https://github.com/katef/libfsm/commit/ff5fb750731778c051d6789e5d67797830f7da7a) as the first bad commit, merged in #393.

reproducing, top DFA is expected, bottom DFA shows the excess state:
![image](https://user-images.githubusercontent.com/1371085/231063120-fdcd3fdb-18ce-4de7-9223-76a034393605.png)

**Comment by silentbicycle** [comment] 2023-04-11 20:39
I'm still investigating the root cause, but `ab*` has the same issue. The divergence precedes minimisation, I think it's during either epsilon removal or determinisation.

**Comment by silentbicycle** [comment] 2023-04-13 22:46
About the original issue:

> Once a match is found, the result should be returned immediately without walking the rest of the string to figure out capture group 0.

That could be doable via extra metadata on end states -- an "ungreedy" end state, in PCRE's terminology -- but we'd need to be really careful with how that should work when combining DFAs.

**Closed** 2023-04-15 01:30 UTC
Labels: bug
